language: python
python:
  - "2.6"
  - "2.7"
  # - "pypy" - doesn't work for bcore

install:
  - git submodule update --init --recursive

script:
  # We only test if the boot stapper can run pgit successfully
  - bin/pgit submodule query
